backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "public/images"
public_folder: "/images"


collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/blog" # The path to the folder where the documents are stored
    extension: "mdx"
    format: "frontmatter"
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    identifier_field: slug
    fields: # The fields for each document, usually in front matter      
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "hidden", default: "slug"}
      - {label: "Author", name: "author", widget: "select", multiple: false, options: ["Team msg91"]}
      - {label: "Publish Date", name: "date", widget: "datetime", required: false}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}     
      - {label: "Tags", name: "tags", widget: "select", multiple: true, options: ["knowledgebase","msg91-api", "marketing-communication", "msg91","cloud-communication", "customer-engagement", "best-practices", "msg91-for-education", "customer-experience", "ai", "transactional-email", "technology-updates", "top-blogs","send-otp-2.0", "msg91-features", "cpaas","msg91-api-viasocket", "addons-&-plugins", "customer-segmentation","msg91-webinar", "msg91-update", "msg91-for-travel","number-masking",send-otp, "transactional-sms", "2fa","programmable-sms"], required: false}
      - {label: "Short Description", name: "description", widget: "string", required: true}
      - {label: "Body", name: "body", widget: "markdown"}
